dset_name: cremp
data_dir: dataset/data
data_aug: True
grid_dim: 96
grid_size: 24  # 这个参数还没有根据cremp数据集修改
resolution: .25
elements: ["C", "H", "O", "N", "F", "S"]
n_channels: 6
n_points: 4_000
subsampling_ratio: 6

# Query points sampling configuration
# targeted_sampling_ratio: grid点和邻近点的比例 (n_grid / n_neighbor)
targeted_sampling_ratio: 2  # 默认值：grid点:邻近点 = 2:1

num_workers: 2
batch_size: 96
lr_enc: 1e-4
lr_dec: 5e-4