dset_name: drugs
data_dir: dataset/data
data_aug: True
grid_dim: 64
resolution: .25
grid_size: 21  # 从 calculate_diameter.ipynb 中计算得到最大直径是33左右
anchor_spacing: 1.5  # 锚点间距，单位为埃
atomic_radius: .5
elements: ["C", "H", "O", "N", "F", "S", "Cl", "Br"]
n_channels: 8
n_points: 1500
subsampling_ratio: 4

num_workers: 2
batch_size: 4
lr_enc: 1e-4
lr_dec: 5e-4