dset_name: drugs
data_dir: dataset/data
data_aug: True
grid_dim: 64 # TODO: 可能覆盖不了全部，但是funcmol里就是设置的这个参数，说明是合理的
resolution: .25

# 20260112/version0
# grid_size: 13  # 从 calculate_diameter.ipynb 中计算得到最大直径是33左右
# anchor_spacing: 1.5  # 锚点间距，单位为埃，大一些可以大幅减小计算量

# 20260112/version1, 20260113/version0
# grid_size: 9
# anchor_spacing: 2.5

# 20260113/version1
grid_size: 7
anchor_spacing: 3

elements: ["C", "H", "O", "N", "F", "S", "Cl", "Br"]
n_channels: 8
n_points: 500 # TODO：后面可以再调大一些，暂时先保留500
subsampling_ratio: 2

# Query points sampling configuration
# targeted_sampling_ratio: grid点和邻近点的比例 (n_grid / n_neighbor)
targeted_sampling_ratio: 0.5  # 默认值：grid点:邻近点 = 2:1

num_workers: 8
batch_size: 20
lr_enc: 2e-5  # 2e-4
lr_dec: 2e-5  # 1e-3
