dset_name: drugs
data_dir: dataset/data
data_aug: True
grid_dim: 64
resolution: .25
grid_size: 9  # 统一的grid_size参数，用于编码器和解码器
anchor_spacing: 1.5  # 锚点间距，单位为埃
atomic_radius: .5
elements: ["C", "H", "O", "N", "F", "S", "Cl", "Br"]
n_channels: 8
n_points: 4_000
subsampling_ratio: 4

num_workers: 2
batch_size: 96
lr_enc: 1e-4
lr_dec: 5e-4