dset_name: drugs
data_dir: dataset/data
data_aug: True
grid_dim: 64 # TODO: 这里需要修改
resolution: .25
grid_size: 11  # 从 calculate_diameter.ipynb 中计算得到最大直径是33左右
anchor_spacing: 2.5  # 锚点间距，单位为埃，大一些可以大幅减小计算量
atomic_radius: .5
elements: ["C", "H", "O", "N", "F", "S", "Cl", "Br"]
n_channels: 8
n_points: 500 # TODO：后面可以再调大一些，暂时先保留500
subsampling_ratio: 4

num_workers: 0  # 暂时禁用多进程以避免Segmentation fault
batch_size: 32  # 减少批次大小以适应多卡训练
lr_enc: 1e-4
lr_dec: 5e-4