dset_name: qm9
data_dir: dataset/data
data_aug: True
grid_dim: 20 # 20*0.25=5，差不多是qm9里的分子中心化后的最大距离
resolution: .25
atomic_radius: .5
elements: ["C", "H", "O", "N", "F"]
n_channels: 5
n_points: 500
subsampling_ratio: 2

num_workers: 4
batch_size: 8
lr_enc: 1e-4
lr_dec: 5e-4