# 一定注意，这里的参数都是针对归一化到[-1,1]的坐标系而言的
sigma: 1
n_query_points: 500
n_iter: 2000
step_size: 0.003
# DBSCAN聚类参数
eps: 0.01      # 邻域半径，单位为Å。越小越严格（原子密集度高就设小），目前调得很小，但是如果使用预测的梯度场，需要适当放大
min_samples: 5 # 至少多少个点才能形成一个"原子簇"
sigma_ratios:
  C: 0.9    # 碳原子，较小的 sigma 使梯度场更集中
  H: 1.3    # 氢原子，较大的 sigma 使梯度场更分散
  O: 1.1    # 氧原子，中等 sigma
  'N': 1.0    # 氮原子，略小于氧原子
  F: 1.2    # 氟原子，略大于氧原子
version: 2
temperature: 0.008 # 温度越高，分布越尖锐，越容易收敛（很可能极端地收敛到单个原子）；温度越低，分布越平缓，越不易收敛